# Generated by Django 4.1 on 2024-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='taxi_car_model_a75eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['username'], name='taxi_driver_usernam_77531b_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['name'], name='taxi_manufa_name_13c564_idx'),
        ),
    ]
